// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFbRISoZXibm7N0fDY_Z2xqvQ4UUBPUAQ',
    appId: '1:382151174839:android:6d44107a55b6060f5d3b32',
    messagingSenderId: '382151174839',
    projectId: 'coffee-5f434',
    storageBucket: 'coffee-5f434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdKiKAMTruthXrMS8ed4Lr4OmYo34APtI',
    appId: '1:382151174839:ios:3e5280cf6a131b2b5d3b32',
    messagingSenderId: '382151174839',
    projectId: 'coffee-5f434',
    storageBucket: 'coffee-5f434.appspot.com',
    iosClientId: '382151174839-jc5hs5dn7nta973pva5qsjireu353hh8.apps.googleusercontent.com',
    iosBundleId: 'com.moonsolution.coffee.coffeeFlutter',
  );
}
